name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Check formatting with black
      run: |
        black . --check
    - name: Test with pytest
      run: |
        PYTHONPATH='.' pytest -vv
    - name: Install serverless
      run: npm install -g serverless
    - name: Serverless AWS authentication
      run: sls config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET_KEY }}
    - name: Install plugins
      run: sls plugin install -n serverless-python-requirements serverless-wsgi
    - name: Create env file
      run: | 
        cat > env.yml << EOF
        ${{ secrets.ENV }}
        EOF
    - name: Deploy
      run: sls deploy
